[package]
name = "redpine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
polling = "3.0.0"
siphasher = "1"

[dev-dependencies]
md5 = "0.7.0"
core_affinity = "0.8.1"
